## Data Encryption and Decryption¶
### Data Encryption:
- Encryption is a security method in which information is a encoded in such a way that only authorised user can read it.
- It uses encryption algorithm to generate ciphertext that can only be read if decrypted.
### Data decrytpion:
- Decryption is the process of taking encoded or encryptedtext and converting it back into text that you (or) the computer can read and understand.

### Types:
|
   ### Symmetric (private key):
- It uses a single key that will be shared among the people who need to receive the message
### Asymmetric(public key):
- Uses a pair of public and private keys to encrypt and decrypt messages.

In [1]:
# Write a funtion to genarate key for encryption
keypath = 'DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
              if i < 6:
                  f.write(str(i)+ ' '+str(i+4)+'\n')
              else:
                   f.write(str(i)+ ' '+str(i-6)+'\n')
    return
generatekey(keypath)

In [2]:
# function to decrypt a datafile
keyfile='DataFiles/key.txt'
def dictionaryKeyFile(keyfile):
    key={}
    with open(keyfile,'r')as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
        return key
def encryptMarksData(datafile,keyfile):
    key=dictionaryKeyFile(keyfile)
    with open(datafile,'r')as f:
        filedata=f.read().split('\n')
    with open('DataFiles/encryptedMarks.txt','w')as f:
        for mark in filedata:
            line=''
            for n in mark:
                line+=key[n]
                f.write(line+'\n')
    return 
datafile='DataFiles/marks.txt'
encryptMarksData(datafile,keyfile)

In [3]:
# Function to decrypt a encrypted a File
def decryptMarksData(encryptedfile, keyfile):
    key = dictionaryKeyFile(keyfile)
    newkey = {}
    for key, value in key.items():
        newkey[value] = key
    with open(encryptedfile, 'r') as f:
        encrypteddata = f.read().split('\n')
    with open('DataFiles/decryptedMarks.txt', 'w') as f:
        for encryptedmark in encrypteddata:
            line = ''
        for n in encryptedmark:
            line +=newkey[n]
            f.write(line + '\n')
    return
encryptedfile = 'DataFiles/encryptedMarks.txt'
import timeit
st = timeit.default_timer()
decryptMarksData(encryptedfile, keyfile)
print(timeit.default_timer()-st)


0.006150410999999911



### Python Libraries for Data Science
Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data. It involves many different disciplines like mathematical and statistical modelling, extracting data from it source and applying data visualization techniques. There are nearly 20 python libraries for Data Science. Top five python libraries are TensorFlow NumPy SciPy Pandas Matplotlib In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies. NumPy: (Numerical Python) Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python. It is used to create multidimensional arrays for fast operations. Use the following import conversion. \Ex: >>import numpy as np NumPy Arrays NumPy have a fixed size of arrays used to store a collection of elements, unlike python lists. There are three types of arrays called 1D, 2D and 3D arrays.

### NUMPY
Creating 1D and 2D arrays using NumPys

In [4]:
import numpy as np
array_1d=np.array([2,4,5,6,7,9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
array_2d=np.array([[2,3,4,],[5,6,7,9]])
print(array_2d)

[list([2, 3, 4]) list([5, 6, 7, 9])]


In [6]:
import numpy as np
li=[1,2,3,'n']
a=np.array(li)
a

array(['1', '2', '3', 'n'], dtype='<U11')

In [7]:
import numpy as np
li=[1,2,3,None]
a=np.array(li)
a.dtype

dtype('O')

In [8]:
import numpy as np
li=[1,2,3,4.0]
a=np.array(li)
a.dtype

dtype('float64')

In [9]:
import numpy as np
li=[1,2,3,4.0]
a=np.array(li)
a

array([1., 2., 3., 4.])

In [10]:
import numpy as np
li=[1,2,3,4.0]
a=np.array(li)
a

array([1., 2., 3., 4.])

In [11]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
import numpy as np
a2 = np.arange(100,10000)
a2

array([ 100,  101,  102, ..., 9997, 9998, 9999])

In [13]:
a2=np.arange(100)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
a2=np.arange(100).reshape(10,10)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### * Inspect the structure and Content of array using “ndarrays”
- The most basic object in NumPy is the “ndarray” object or simply an “array”.
- The ndarray has important attributes. They are
- ndarray.ndim: No of dimensions of array referred as “rank”.
- ndarray.shape: Returns the length of the array in tuple.
- ndarray.size: Returns the size of an array.
- ndarray.dtype: We can create or specify “dtype” using standard Python types. NumPy provides types like numpy.int32, numpy.int16, and numpy.float64
- ndarray.itemsize: Returns the size in bytes of each element in an array
- Create a 2D Array and inspect size, shape, dimensions and dtype of the array.

In [15]:
# Create a 2d array and inspect size,shape,dimensions dtype of the array
import numpy as np
array1=np.random.randint(0,2,size=(3,3))
array1[2][2]
print('Shape:',array1.shape)
print('Size:',array1.size)
print('dtype:',array1.dtype)
print('itemsize:',array1.itemsize)
print('Data:',array1.data)
array1

Shape: (3, 3)
Size: 9
dtype: int32
itemsize: 4
Data: <memory at 0x000001CB01900990>


array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [16]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
a[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [ ]:
np.ones?

In [18]:
array1 = [[1,2,3,4],[5,6,7,8]]
a1 = np.array(array1)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# Create an array of 1's
import numpy as np  
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a.dtype

dtype('float64')

In [21]:
print("Shape:",a1.shape)
print("Data Type:",a1.dtype)
print("Size:",a1.size)
print("Dimention:",a1.ndim)

Shape: (2, 4)
Data Type: int32
Size: 8
Dimention: 2


In [22]:
import numpy as np  
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
b=[[1,2,3],[1030,300,3300],[11,56,60]]
c=np.array(b)
c

array([[   1,    2,    3],
       [1030,  300, 3300],
       [  11,   56,   60]])

In [24]:
d=c+1
d

array([[   2,    3,    4],
       [1031,  301, 3301],
       [  12,   57,   61]])

In [25]:
# We can perform arithematic operations in Numpy like Addition,subtraction,product,division
a=np.arange(1,7).reshape(2,3)
b=np.arange(5,11).reshape(2,3)
print(a)
print(b)
print(a+b,'\n')
print(a/b)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]]
[[ 6  8 10]
 [12 14 16]] 

[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [26]:
a = [60,66,70]
a1 = np.array(a)
print(np.sqrt(a1))
print(np.sin(a1))
print(np.cos(a1))
print(np.log(a1))

[7.74596669 8.1240384  8.36660027]
[-0.30481062 -0.02655115  0.77389068]
[-0.95241298 -0.99964746  0.6333192 ]
[4.09434456 4.18965474 4.24849524]
